apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gitlab-cicd
spec:
  rules:
  - host: tekton.cicd.devops.en.internal
    http:
      paths:
      - backend:
          serviceName: el-gitlab-cicd
          servicePort: 8080
        path: /


